### ISSUE TITLE
GPU not utilized

### ISSUE THREAD

**Issue by alexhuang2020** [deep-learning-with-pytorch/dlwpt-code#60]
I have a GTX 1050 Ti, and I checked:
  torch.cuda.device_count()
  1
  torch.cuda.is_available()
  True
However nvidis-smi reports 0% GPU usage when I ran "run('training.LunaTrainingApp', '--epochs=1')"

However, when I ran 
    import torch
    a = torch.rand(20000,20000).cuda()
    while True:
        a += 1
        a -= 1
GPU utility goes up to close to 100%.

What could be the problem?
Thanks.

**Comment by alexhuang2020** [comment]
Issue resolved. 
If anyone else has the same issue, follow this link: 
https://discuss.pytorch.org/t/no-gpu-utilization-although-cuda-seems-to-be-activated/40964/26

**Comment by alexhuang2020** [comment]
Now I loaded 10,000 samples to Google Colab with GPU, and ran "run('training.LunaTrainingApp', '--epochs=1')"
GPU utility is also 0%.

**Comment by sfleisch** [comment]
The code is wrong in the function "initModel" in training.py.
Current code:

     ```
    def initModel(self):
        model = LunaModel()
        if self.use_cuda:
            log.info("Using CUDA; {} devices.".format(torch.cuda.device_count()))
            if torch.cuda.device_count() > 1:
                model = nn.DataParallel(model)  #!  Yeah this doesn't work. Stays on the CPUs.
            model = model.to(self.device) #Not exactly sure what this is doing.
        return model
    ```
Needs to be:

     ```
    def initModel(self):
        model = LunaModel()
        if self.use_cuda:
            log.info("Using CUDA; {} devices.".format(torch.cuda.device_count()))
            model = model.to(self.device)  #Transfer to multiple devices must come from a GPU.
            if torch.cuda.device_count() > 1:
                model = nn.DataParallel(model, device_ids=range(torch.cuda.device_count()))   #Need the device list!
        return model
     ```

**Comment by dmor1928** [comment]
> The code is wrong in the function "initModel" in training.py. Current code:
> 
> ```
>  ```
> def initModel(self):
>     model = LunaModel()
>     if self.use_cuda:
>         log.info("Using CUDA; {} devices.".format(torch.cuda.device_count()))
>         if torch.cuda.device_count() > 1:
>             model = nn.DataParallel(model)  #!  Yeah this doesn't work. Stays on the CPUs.
>         model = model.to(self.device) #Not exactly sure what this is doing.
>     return model
> ```
> ```
> 
> Needs to be:
> 
> ```
>  ```
> def initModel(self):
>     model = LunaModel()
>     if self.use_cuda:
>         log.info("Using CUDA; {} devices.".format(torch.cuda.device_count()))
>         model = model.to(self.device)  #Transfer to multiple devices must come from a GPU.
>         if torch.cuda.device_count() > 1:
>             model = nn.DataParallel(model, device_ids=range(torch.cuda.device_count()))   #Need the device list!
>     return model
>  ```
> ```

Thank you! But how does the order of the if-statement affect GPU utilisation if you only have one GPU? I was struggling to get the model to run on my single GPU, but your answer has solved it. I don't understand how it would make a difference.
